[package]
name = "cbor-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_cbor = "0.11"
serde = { version = "1.0", features = ["derive"] }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "cbor_bench"
harness = false
